version: '2.1'

services:
  blockchain5000:
    build: .
    container_name: blockchain5000
    image: blockchain5000
    restart: always
    ports:
      - "5000:5000"
    network_mode: "host"

  blockchain5001:
    build: .
    container_name: blockchain5001
    image: blockchain5001
    restart: always
    ports:
      - "5001:5001"
    network_mode: "host"